const ColorData = [
   // {id: 1, BackgroundColor: "#7743DB"},
   // {id: 2, BackgroundColor: "#59C1BD"},
   // {id: 3, BackgroundColor: "#FEBE8C"},
   // {id: 4, BackgroundColor: "#C060A1"},
   // {id: 5, BackgroundColor: "#9C254D"},
   {
      id: 6,
      BackgroundColor: "#5B9A8B",
      PrimaryColor: "#101920",
      SecondaryColor: "#FFE715",
      TextColorPrimary: "#97FFF4",
      TextColorSecondary: "black",
      InActiveColor: "#FFFFFF",
      IconColor: "#FFE715",
      BarStyle: "dark-content",
      BottomSheetColorBG: "#183D3D",
      DrawerTextColor: "#FFFFFF",
      drawer: {
         drawerActiveBackgroundColor: "#101920",
         drawerActiveTintColor: "#FFE715",
         drawerInactiveTintColor: "#101920",
      },
   
},
   {
      id: 7,
      BackgroundColor: "#16213E",
      PrimaryColor: "#FFC7EA",
      SecondaryColor: "#FFE5AD",
      TextColorPrimary: "#000",
      TextColorSecondary: "#000",
      InActiveColor: "#8E8E8F",
      IconColor: "#000",
      BarStyle: "light-content",
      BottomSheetColorBG: "#160040",
      DrawerTextColor: "#FFFFFF",
      drawer: {
         drawerActiveBackgroundColor: "#FFC7EA",
         drawerActiveTintColor: "#000",
         drawerInactiveTintColor: "#FFFFFF",
      },
   },
   {
      id: 8,
      BackgroundColor: "#000000",
      PrimaryColor: "#8B6AFE",
      SecondaryColor: "#BEADFA",
      TextColorPrimary: "#FFFFFF",
      TextColorSecondary: "#000",
      InActiveColor: "#8E8E8F",
      IconColor: "#FFFFFF",
      BarStyle: "light-content",
      BottomSheetColorBG: "#160040",
      drawer: {
         drawerActiveBackgroundColor: "#8B6AFE",
         drawerActiveTintColor: "#000",
         drawerInactiveTintColor: "#FFFFFF",
      },
   },
];
export default ColorData;
