const ColorData = [
   {id: 1, BackgroundColor: "#7743DB"},
   {id: 2, BackgroundColor: "#59C1BD"},
   {id: 3, BackgroundColor: "#FEBE8C"},
   {id: 4, BackgroundColor: "#C060A1"},
   {id: 5, BackgroundColor: "#9C254D"},
   {id: 6, BackgroundColor: "#008000"},
   {
      id: 7,
      Color: "#000000",
      TabBackgroundColor: "red",
      BackgroundColor: "#16213E",
      PrimaryColor: "#FFC7EA",
      SecondaryColor: "#FFE5AD",
      TextColorPrimary: "#000",
      TextColorSecondary: "red",
      InActiveColor: "#8E8E8F",
      IconColor: "#FFFFFF",
      BarStyle: "light-content",
      BottomSheetColorBG: "#160040",
      DrawerTextColor: "#FFFFFF",
   },
   {
      id: 8,
      Color: "#000000",
      TabBackgroundColor: "red",
      BackgroundColor: "#000000",
      PrimaryColor: "#8B6AFE",
      SecondaryColor: "#BEADFA",
      TextColorPrimary: "#FFFFFF",
      TextColorSecondary: "#000",
      InActiveColor: "#8E8E8F",
      IconColor: "#FFFFFF",
      BarStyle: "light-content",
      BottomSheetColorBG: "#160040",
   },
];
export default ColorData;
